### ISSUE TITLE
jquery execution

### ISSUE THREAD

**Issue by mhorrie** [mcsheaj/SPEasyForms#66]
I need some jquery to be execute after the speasy form has been fully loaded. Unfortanatly I don't succeed and my jquery is fired before the form was finished. 

I do use the command $(function () {...} so that code is just executed after the page has been loaded.
I even use a Timeout...

Do I need to reorder some script-calls?

**Comment by mcsheaj** [comment]
The problem is that SPEasyForms is doing a lot of it's work on document ready, so putting your code in document ready doesn't guarantee running after SPEasyForms in fact it almost guarantees running concurrently with SPEasyForms.  The best way to achieve what you're trying to do is to put your JavaScript in an HTML Snippet container, or ideally in a JavaScript file that is loaded in an HTML Snippet container.  If this container is at the bottom of your form, the rest of the form will have rendered before your JavaScript has been called.

Joe

**Comment by mhorrie** [comment]
Ok thanks! I will try that, but because my site collections exist of lots and lots of 'custom' pages, I will need many HTML Snippet containers, wich will make everything unstructured and messy. Are you sure that there is no way I can influence the order in wich SPEasyforms is excecuted.

**Comment by mhorrie** [comment]
hmmm this will not work for me. Pages like NewItem.aspx and EditForm.aspx only have one section so I can't choose where to place the snippet. And beside that it wil make my work very complex because of the quantity (I now use only one custom.js for all custom things I need to be done, and it is executed on documentready). Furthermore, the code I want to be executed after SPEasyforms, does have to scaffold on to the SPEasyform output.

So I'm really looking for some option to run code after SPEasyform is ready with its work on the form.

**Comment by mcsheaj** [comment]
SPEasyForms is loaded by SharePoint via custom actions.  All of the scripts are loaded via script source custom actions, and the init method that actually does the work is called via a script block custom action.  This is called by SharePoint after document ready, so there is nothing I can do to control the order of execution exactly, at least not without completely rewriting the application because the page life cycle is controlled by SharePoint.  

However, custom actions are loaded by SharePoint in an order that is determined by a sequence number that you specify when you create the custom action (sort of...).  In reality, I think all script source custom actions are loaded before any script block custom actions.  The script block custom action that calls init uses the sequence number 57741, so that's the highest sequence number I use.  Theoretically, you can load a script block custom action with a sequence number higher than 57741 and you will be called after SPEasyForms is initialized, but I haven't actually tested this.

I can play around with it and provide more detailed info but I'm speaking at SharePoint Saturday Chevy Chase this weekend and SharePoint Saturday Atlanta next weekend, so I'm not sure when I can get to it.  But any solution that uses custom actions to load JavaScript is always going to be called after document ready and there is nothing you can do to change that.  In fact, SPEasyForms wouldn't work if that weren't true, because I need SharePoint to be done building the page before I'm called.

Joe

**Comment by mcsheaj** [comment]
Sorry to take so long getting back to you.  The only real solution for what you're trying to do is a monkey patch.  It's the technique I used for hot fixes in the 2014 version of SPEasyForm.  Basically, you need to replace my init method, but keep a reference and call it when you want to like:

```
(function ($, undefined) {

    // return without doing anything if SPEasyForms has not been loaded
    if (!$ || !$.spEasyForms) return;

    /*
     *  Modified to override contextReady instead of init.
     */
    $.spEasyForms.origcontextReady = $.spEasyForms.contextReady;

    $.spEasyForms.contextReady = function (options) {
        // do whatever you want before speasyforms

        // call the original SPEasyForms init method
        $.spEasyForms.origcontextReady(options);

        // do whaterver you want afeter speasyforms (mostly)
    };

})(typeof (spefjQuery) === 'undefined' ? null : spefjQuery);

```
Now the trick is to get your JavaScript loaded after my JavaScript is loaded but before my init method is called.  Fortunately, there's an easy way to achieve this that's built into SPEasyForms.  

Just go to **Site Settings -> Site Collection Settings -> SPEasyForms** in your root web and enter the path to your JavaScript file into the **Additional files to load** text area.  Your script must be located some place within the site collection (that's a hard requirement for script links in SharePoint), and you should put in the path to it as something like **~sitecollection/Style Library/yourawesomescript.js**, and it will get loaded after mine but before init is called.

I never loved this technique for the hot fixes, it's a bit brute force, but it works.  I had considered adding calls before and after init to some other function if and only if it exists, kind of like SharePoints PreSaveAction thing, but I never got around to it.

BTW, I said mostly in my second comment because there still might be some minor asynchronous stuff going on with SPEasyForms, but for the most part once init returns the forms is structurally complete.

Joe

**NOTE: Modified 8/17/2018 because this didn't really work. The modification is overriding contextReady instead of init.  init is where the action starts for SPEasyForms, but it ends with 4 asynchronous Ajax calls.  When those calls resolve, contextReady is called back, and the actual rendering occurs.**
