### ISSUE TITLE
Groups Issue

### ISSUE THREAD

**Issue by niceitGH** [mcsheaj/SPEasyForms#67]
I'm trying to hide a field in SharePoint O365 from "Team Site Members" group. This group is populated by "Everyone Except External Users". The field is not hidden unless I specifically add the test user to the Group. Is this an issue with SPEasyForm or something else in SharePoint Online? I hope I missed something because adding 300 odd O365 users to the Group would be a admin nightmare.

**Comment by mcsheaj** [comment]
Unfortunately, this is a known limitation, not just for SharePoint online but for all versions of SharePoint.  All methods that SharePoint exposes (i.e. REST, CSOM, etc.) to determine what groups a user is in do not return any groups that the user is in only indirectly (i.e. through membership in an Active directory group).  

I know this severely limits the usefulness of this feature, but there is absolutely nothing that I can do about it in a client-side solution.  I have thought about writing a server-side web service to correctly handle indirect membership in a group (it's not that hard server-side), blogging about how to deploy it, and providing a way to configure SPEasyForms to use it, but this wouldn't even help you because there is no way to deploy server-side code to SharePoint Online.

Ideally, Microsoft should fix their APIs so they return all groups in which the user is a member, either indirectly or directly, but it has been this way since 2007 so I'm not holding my breath for them to change it.  Keep in mind that I said "fix", but Microsoft doesn't actually consider it to be broken.  

I should document this limitation in the online help, but that's about the best I can do.

Joe

**Comment by niceitGH** [comment]
Thank you Joe for your quick response. Saves me from fruitless hours of further testing and googling. The other features of the app look very useful.
It does occur to me that SharePoint is able to determine "Permission Levels" given to a user (even indirectly added to a Group) through Site Settings > Site permissions > Check Permissions.
I wonder if there is any way of leveraging that function to determine Group membership? It would certainly make the app more functional to the point that I and many others would be willing to pay for the tool.

**Comment by mcsheaj** [comment]
Yeah, there's no question that it would be easy enough for them to do it on the server side.  The web service I talk about above is something I have written for specific clients to overcome the same deficiency in the SharePoint APIs.  

They can't really claim it's a security thing, because then I shouldn't be able to see groups to which the user belongs directly either.   And anyway, I'm executing code as the current user asking for the current user's groups?  Through the UI, the current user can not only see what groups they are in, but also who else is in those groups?  

Microsoft does now have a site on which they collect user feedback on SharePoint feature requests called the [SharePoint User Voice](https://sharepoint.uservoice.com/).  If enough people vote for it, supposedly they might work on it and it would certainly come to Office 365 first.  Perhaps someone should request it? ;)

Joe
