### ISSUE TITLE
Custom errorhandling in easyforms

### ISSUE THREAD

**Issue by Perneel** [mcsheaj/SPEasyForms#71]
Hi,

We were wondering if the following is possible:

The scenario is as follows:

- We have the default Save button to save the form without any validation (all fields are optional)
- We use a custom json config file to set some fields as required.
- When the "Indienen" button is pressed, we validate all fields based on our config.

By default, SPEasyForms shows input errors for required fields with a red dashed border and the according accordion is automatically expanded:

![image](https://user-images.githubusercontent.com/4124110/35815006-d1fa9828-0a97-11e8-86ba-66b53103bbaa.png)

We wondered if it is possible to apply this behaviour with our custom config:

1. We pressed the 'Indienen' button, multiple fields doesn't have the required values:

![image](https://user-images.githubusercontent.com/4124110/35815118-1121c012-0a98-11e8-9b1a-e5a06d50f74e.png)

2. When manually expanding the accordions, we can see our custom error messages:

![image](https://user-images.githubusercontent.com/4124110/35815200-3fecb992-0a98-11e8-928d-6bad8accbd57.png)

Is it possible to trigger the red dashed border to the tabs and the first accordion where an error occured expanded by calling a specific function?

**Comment by mcsheaj** [comment]
Hello,

Yes, it should be possible.  By default, SPEasyForms implements a preSaveAction, which is called automatically when you hit the save button.  This call happens after the form has been validated, so SPEasyForms looks for things that look like an error.  In a standard SharePoint form, error messages are produced in a span where role='alert', so that's what SPEasyForms is looking for ("span[role='alert']").

If your error messages match this, then SPEasyForms can highlight your errors too, but of course first it has to be called, which isn't happening automatically on your Indienen button.  SPEasyForms overrides the default PreSaveItem method from Microsoft, so if you add a call to:

PreSaveItem()

to the click handler for Indienen, anywhere after your validation errors have been placed on the page, the Indienen button should then work the same as the save button.

Joe

**Comment by mcsheaj** [comment]
I just realized that may not work for you, because my preSaveItem method calls:

SPClientForms.ClientFormManager.SubmitClientForm

which is the SharePoint method that performs the OOB validation, and I'm guessing you don't want the OOB validation to be performed (plus it may interfere with your form submission).

If that's the case, you can do something a little more SPEasyForms specific, and call my method that highlights validation errors directly, like: 

spefjQuery.spEasyForms.containerCollection.highlightValidationErrors()

if it sees anything like "span[role='alert']" it should highlight the tab or card it's on.  So make your error messages look like SharePoint error messages (i.e. spans with role='alert'), and make sure your error messages are in the DOM before you call highlightValidationErrors() and it should work.

Joe

**Comment by Perneel** [comment]
Superb, works like a charm :) Is there also a method to hide the validation errors?
If a tab contains errors, it applies the css correcly, however, when the errors get fixed and we press the 'Indienen' knop again, the css stays applied.

With errors:
![image](https://user-images.githubusercontent.com/4124110/36089159-b5fdbb44-0fda-11e8-990e-9e607378d996.png)

After the errors on that tab are fixed, and pressing the 'Indienen' knop again:
![image](https://user-images.githubusercontent.com/4124110/36089207-f8732450-0fda-11e8-9826-7a9ee2730a10.png)

**Comment by mcsheaj** [comment]
highlightValidationErrors() should add a CSS class to a container when it contains validation errors, and remove it when it doesn't.  The sequence of events is like this:

- User clicks submit
- SharePoint code detects validation errors and inserts a span[role='alert'] with the error text
- SPEasyForms sees the span[role='alert'] and highlights the encapsulating container by adding a class to it (via highlightValidationErrors()).
- User corrects the problem and hits submit again
- SharePoint detects that there is no validation error and removes the span[role='alert'] from the DOM completely
- SPEasyForms sees that there no span[role='alert'] elements in the DOM and removes the highlight class (again via highlightValidationErrors())

If you're validation works like the OOB validation, SPEasyForms should just work, so every time you call highlightValidationErrors() it should highlight containers with validation problems and remove highlighting from containers with no validation errors.

But keep in mind that hiding the validation errors isn't good enough, SPEasyForms doesn't care about the visibility of the span[role='alert'], it's mere presence indicates an error.  It needs to be removed from the DOM completely, or at least altered in such a way that SPEasyForms won't see it as a validation error any more (i.e. you could just remove [role='alert'] from the span).

Joe

**Comment by Perneel** [comment]
Ah yes, I forgot to reset the role. My bad, works like a charm now :) Thanks for the explanation and keep up the good work!
