### ISSUE TITLE
Missing SPEasyForms icon in Ribbon for specific list

### ISSUE THREAD

**Issue by Perneel** [mcsheaj/SPEasyForms#80]
I've installed the SPEasyForms solution on an existing site (SP2013 on prem). I have two lists on this site. One list fails to show the SPEasyForms icon in the ribbon. The difference I see between both lists is that the 'faulty' list has a calculated field. Other (standard SP) field types used are Text, Number, Lookup, Date, Choice and Person fields.

Any idea what could be the cause of this? If you need more info, let me know as I'm not sure which data I should provide in this case :)

**Comment by mcsheaj** [comment]
Programmatically, SPEasyForms calls `spefjQuery.spEasyForms.isConfigurableList()` to determine if the ribbon should be displayed. Under the hood, that does the following checks:

1. If the list is a survey or discussion, return false.
2. If I cannot determine the current list context, return false.  On any view of any classic list, I should be able to easily get the current list context.
3. If an exception occurs while trying to check this, I expect the button is hidden.
4. Otherwise, return true, and the ribbon button should be enabled.

If you go to the list settings page, does SPEasyForms show up there? Should be on the first row of links, right under validation settings usually, and may not appear until a second or so after page load.

Joe

**Comment by mcsheaj** [comment]
No problem, thanks for getting back to me.

Joe
