### ISSUE TITLE
cascading issue 

### ISSUE THREAD

**Issue by research-bit** [mcsheaj/SPEasyForms#83]
Hello, I have been trying to create a cascading list following your 4th video on configuring field adapters, however each time I choose my relationship list, I am not able to choose my parent and child columns. My relationship list is grouped together with the parent and child columns as you have done in your tutorial, therefore I was wondering if you knew why I am not able to fill in these fields/what I can do on my end to fix this problem. Thanks!

**Comment by mcsheaj** [comment]
I only have one guess as to what the problem may be.  SPEasyForms caches each list the first time it reads it. If you add columns after that cache, you won't see them in SPEasyForms until you either hit the clear cache button or completely close and open your browser. I say completely close because these days a lot of browsers continues running even after you've closed all windows. 

If that isn't the problem, then I need more information, like screenshots of the lookup list (both the default view and the settings page/columns), the same for the list where you're configuring the lookup, a screenshot of what you're seeing in the dialog when you try to configure the cascading lookup in SPEasyForms, and what versions of SharePoint and SPEasyForms you are running.

**Comment by mcsheaj** [comment]
Closed for inactivity.
