### ISSUE TITLE
Tabs Adapter - Showing tabs without columns

### ISSUE THREAD

**Issue by Marouanebouzoubaa** [mcsheaj/SPEasyForms#84]
Hello,

The Tabs adapter do not show any tab that do not contain at least a column. I would like to change this behavior because I want to add an html snippet to do custom things without adding columns, the problem is that it forces me to put a column otherwise the tab disappears,  I know that it uses jquery UI, but this is not the default behavior of I could not find something on the web to customize the jquery ui tabs component. I guess this was implemented in SPEasyFroms somewhere, but i could not figure out.

Could you please tell me how to keep a tab showing when containing Html snippets/ or even without anything inside the tab ? 

Cheers,

Marouane

**Comment by mcsheaj** [comment]
Sorry Marouane, 

Got a little busy and haven't been keeping up.  Yes, this is not a jQuery UI thing, it was implemented in SPEasyForms, and dates back to before there was an HTML snippets container.

It's implemented in the individual containers, since the details of the implementations are isolated from the rest of the code.  The method where it occurs is called postValidationAction, and was originally intended for doing custom validation in SPEasyForms, but that was never implemented. If you override that action, you can prevent that behavior, so something like:

`spefjQuery.spEasyForms.containerCollection.containerImplementations.tabs.postTransform = function() {};`

should negate that function and prevent that behavior. Note that hiding tabs that don't have fields is critical functionality for lists that contain multiple content types, or at least can be, so I wouldn't want to change that behavior globally. But if you did it in a script block in your HTML snippet, it would only change the behavior for that one list.

Joe

**Comment by Marouanebouzoubaa** [comment]
Hi, Glad hearing from you. I will try your suggestion. Thx.

**Comment by Marouanebouzoubaa** [comment]
Hi, i have placed the call in one of my master page js scripts and it did the trick (tabs are visible). BUT, HTML snipets inside tabs without any field are not interpreted/visible ! do you have an idea ?

Thank you very much.

Marouane
